#!/usr/bin/env Rscript
# 96 well spectrophotometer data analysis
# Copyright Jackson M. Tsuji (Neufeld Lab PhD student), 2018
# Created Nov 10th, 2016
# Description: Imports and processes data from the Neufeld lab 96 well plate reader

#####################################################
## User variables: #################################
RUN_COMMAND_LINE <- TRUE # If selected, all user input here is ignored, and terminal-based input is expected instead.

# Set other user variables here
if (RUN_COMMAND_LINE == FALSE) {
  setwd("/Users/JTsuji/Research_General/Bioinformatics/02_git/96-well-spec-analysis/") # your working directory where files are stored
  plate_data_filename <- c("testing/input/example_raw_plate_data_1.txt") # Raw data from the 96 well plate reader ('column/both' format, with default encoding)
  sample_metadata_filename <- "testing/input/example_sample_metadata.tsv" # Not needed if pre_parsed_data_file == FALSE
  pre_parsed_data_file <- NULL # This is an optional setting to import pre-parsed raw data files (e.g., produced by this script previously) to re-analyze for sample concentrations (e.g., after making custom edits).
  # Set to NULL if you want to process raw files (plate_data_filename, sample_metadata_filename) instead.
  # Otherwise, set plate_data_filename and sample_metadata_filename to NULL, then set this variable to the name of the pre-parsed raw data file you want to re-analyze.
  # The script WILL NOT RUN if plate_data_filename, sample_metadata_filename, and pre_parsed_data_file are all set
  
  force_curve_through_zero <- TRUE # force the standard curve plots to go through (0,0)? (Recommended TRUE)
}

#####################################################
## Load required packages: ##########################
# TODO - add check function to see if these have been installed, and exit if not
library(getopt, quietly = TRUE, warn.conflicts = FALSE)
library(glue, quietly = TRUE, warn.conflicts = FALSE)
library(plyr, quietly = TRUE, warn.conflicts = FALSE)
suppressMessages(library(dplyr, quietly = TRUE, warn.conflicts = FALSE))
library(ggplot2, quietly = TRUE, warn.conflicts = FALSE)
library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(reshape2, quietly = TRUE, warn.conflicts = FALSE)
library(xlsx, quietly = TRUE, warn.conflicts = FALSE)
#####################################################

SCRIPT_VERSION <- "v0.3" # to match git tag

parse_command_line_input <- function() {
  ### Grab arguments
  # Arguments required:
  # -i input plate_data_filename
  # -m input sample_metadata_filename
  # -p pre_parsed_data_file
  # -z force_curve_through_zero
  # -o output_filenames_prefix (for output files)
  params <- matrix(c('plate_data_filename', 'i', 2, "character",
                     'sample_metadata_filename', 'm', 2, "character",
                     'output_filenames_prefix', 'o', 2, "character",
                     'pre_parsed_data_file', 'p', 2, "character",
                     'force_curve_through_zero', 'z', 2, "character",
                     'help', 'h', 2, "character"), byrow=TRUE, ncol=4)
  
  opt <- getopt(params)
  
  # If no inputs files were provided, go to help
  if ( is.null(opt$plate_data_filename) && is.null(opt$sample_metadata_filename) && is.null(opt$pre_parsed_data_file) ) {
    opt$help <- TRUE
  }
  
  # If help was called, print help message and exit
  if ( !is.null(opt$help) ) {
    
    cat("\n96_well_spec_analysis.R: Analyzed 96 well spec data generated by the Neufeld lab's plate reader.\n")
    cat("Copyright Neufeld Lab, 2018\n")
    cat("Contact Jackson M. Tsuji (jackson.@uwaterloo.ca) for bug reports or feature requests.\n")
    cat(paste("Version: ", SCRIPT_VERSION, "\n\n", sep = ""))
    
    cat(getopt(params, usage = TRUE))
    
    cat("\n")
    
    # TODO - add these details
    # cat("Details:\n", "-atlas_table\t\t\tFilepath for TSV-format ATLAS annotations table. [Required]\n",
    #     "-featureCounts_table\t\tFilepath for TSV-format featureCounts count file. [Required]\n",
    #     "-output_file\t\t\tFilepath for output TSV-format annotations file. [Required]\n\n")
    
    quit(status = 1)
  }
  
  # Determine if a plate file and metadata file were provided versus a pre-parsed file
  if (is.null(opt$plate_data_filename) == FALSE | is.null(opt$sample_metadata_filename) == FALSE) {
    input_mode <- "raw"
  } else if (is.null(opt$pre_parsed_data_file) == FALSE) {
    input_mode <- "pre-parsed"
  } else if ((is.null(opt$plate_data_filename) == FALSE | is.null(opt$sample_metadata_filename) == FALSE) && is.null(opt$pre_parsed_data_file) == FALSE ) {
    stop("ERROR: Cannot have the '-p' flag set at the same time as '-i' or '-m'. Exiting...")
  } else {
    stop("Something unexpected went wrong related to the '-p', '-i', and '-m' flags being set improperly. Exiting...")
  }
  
  # Exit if required input tables are not provided (different for different input modes)
  if (input_mode == "raw") {
    if ( is.null(opt$plate_data_filename) ) {
      stop("Input plate data filepaths required. Try -h for help message.")
    }
    if ( is.null(opt$sample_metadata_filename) ) {
      stop("Input sample metdata filepath required. Try -h for help message.")
    }
  } else if (input_mode == "pre-parsed") {
    if ( is.null(opt$pre_parsed_data_file) ) {
      stop("Input pre-parsed absprbance/metadata table filepath required. Try -h for help message.")
    }
  } else {
    stop("Something unexpected went wrong related to the '-p', '-i', and '-m' flags being set improperly. Exiting...")
  }
  
  # Provide defaults for optional inputs if not provided
  
  if ( is.null(opt$force_curve_through_zero) ) {
    opt$force_curve_through_zero <- TRUE
  }
  if ( is.null(opt$output_filenames_prefix) ) {
    opt$output_filenames_prefix <- NA # Signal to determine properly later
  }
  
  # Make variables from provided input and save as global variables (<<-)
  # TODO - make CAPS
  plate_data_filename <<- opt$plate_data_filename
  sample_metadata_filename <<- opt$sample_metadata_filename
  pre_parsed_data_file <<- opt$pre_parsed_data_file
  force_curve_through_zero <<- opt$force_curve_through_zero
  output_filenames_prefix <<- opt$output_filenames_prefix
  
}


# Description: parses one plate from an input file
parse_individual_plate <- function(unparsed_plate_data, plate_ending_line, plate_num) {
  # test data
  # unparsed_plate_data <- unparsed_data
  # plate_ending_line <- plate_endings[1]
  # plate_num <- 1
  
  # Get the lines where the absorbance and well data is kept for the plate
  plate_lines <- c((plate_ending_line - 2), (plate_ending_line -1))
  
  # Pull the lines from the unparsed file
  plate_unparsed <- unparsed_plate_data[plate_lines]
  
  # Eliminate the first two tabs
  plate_unparsed <- gsub("^\t\t", "", plate_unparsed)
  
  # Make a table out of the absorbance data
  plate_parsed <- strsplit(plate_unparsed, "\t")
  names(plate_parsed) <- c("Well", "Absorbance")
  plate_parsed$Absorbance <- as.numeric(plate_parsed$Absorbance)
  plate_parsed <- data.frame("Plate_number" = plate_num, 
                             "Well" = plate_parsed[[1]], 
                             "Absorbance" = plate_parsed[[2]], 
                             stringsAsFactors = FALSE)
  
  return(plate_parsed)
}

# Description: loads one input file (can contain multiple plates)
parse_input_file <- function(file_name) {
  # Internal dependency functions: 'parse_individual_plate'
  
  # Read the vectorized input - got code here from the readLines help file
  con <- file(file_name, encoding = "UTF-16LE") # Assumed encoding based on the output of the plate reader software
  # TODO - try to detect this (or throw an error if it doesn't work?)
  unparsed_data <- readLines(con)
  close(con)
  # unique(Encoding(A))
  
  ### Parse the input
  # Eliminate the first line and last line (extraneous)
  unparsed_data <- unparsed_data[-c(1, length(unparsed_data))]
  
  # Determine the number of plates
  plate_endings <- grep("^~End", unparsed_data)
  number_of_plates <- length(plate_endings)
  cat(paste("File ", file_name, ": found ",number_of_plates," plates' worth of plate data.\n", sep = ""))
  
  # Call function to get the data for each plate
  plate_data <- lapply(1:number_of_plates, 
                       function(x) {parse_individual_plate(unparsed_data, plate_endings[x], x)})
  
  # Combine into a single data frame
  plate_data <- dplyr::bind_rows(plate_data)
  
  return(plate_data)
}

# Description: adds sample metadata to the parsed absorbance data
add_sample_metadata <- function(all_plate_data, metadata_filename) {
  ## Import sample order data
  plate_order <- read.table(metadata_filename, sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  
  # Check if required columns exist. If they do not, exit early.
  required_colnames <- c("Plate_number", "Well", "Sample_name", "Sample_type", "Blanking_group", "Dilution_factor", "Standard_conc")
  req_col_test <- unique(required_colnames %in% colnames(plate_order))
  if (length(req_col_test) != 1 | req_col_test[1] == FALSE) {
    stop("ERROR: Missing required column in sample naming file (see README.md). Exiting...")
  }
  
  ## Check if the sample naming and plate abosorbance data have the same number of plates, and throw a warning if not
  if (identical(unique(plate_order$Plate_number), unique(all_plate_data$Plate_number)) == FALSE) {
    warning("Number of plates in raw data files and sample naming sheet do not match. NA values will be placed where there are unmatched plates and may cause unexpected behaviour.")
  }
  
  ## Join sample order data with absorbance data
  all_plate_data_merged <- dplyr::full_join(all_plate_data, plate_order, by = c("Well","Plate_number"))
  
  return(all_plate_data_merged)
}

# Description: fully parses and integrates raw plate absorbance data and metadata
parse_raw_data <- function(plate_data_filename, sample_metadata_filename) {
  
  # Error if nothing provided for input
  if (length(plate_data_filename) == 0) {
    stop("ERROR: no input raw plate data file detected")
  }
  
  # Parse input file
  plate_data <- parse_input_file(plate_data_filename)
  
  # Add sample naming data
  plate_data_merged <- add_sample_metadata(plate_data, sample_metadata_filename)
  
  return(plate_data_merged)
  
}

# Description: generates summary stats for blanking group for each plate.
# Throws a warning if SD > 10% of mean
# MUST be one blank per plate for each group in that plate (good form)
summarize_blanks <- function(plate_table) {
  ### Summarize blanks
  blanks_raw <- filter(plate_table, Sample_type == "Blank")
  # TODO - check if 'Standard_conc' is really needed.
  blanks_grouped <- group_by(blanks_raw, Blanking_group, Sample_name, Plate_number)
  blanks_summ <- summarise(blanks_grouped, Blank_ave_abs = mean(Absorbance), Blank_stdDev_abs = sd(Absorbance))
  
  # Throw a warning if SD > 10% of mean
  for (i in 1:nrow(blanks_summ)) {
    if (blanks_summ$Blank_stdDev_abs[i] > (blanks_summ$Blank_ave_abs[i]) / 10) {
      warning(paste("Plate ", unique(plate_table$Plate_number), ": ", blanks_summ$Blanking_group[i], ": standard deviation is > 10% of mean of replicate blanks. Data could be fishy...", sep = ""))
    }
  }
  
  return(blanks_summ)
}

# Description: blanks the absorbances of all standards/samples
# Return: data table with the blanked absorbances
blank_absorbances <- function(plate_table, summarized_blanks) {
  
  # Remove sample name column from blank to avoid issue in joining
  summarized_blanks$Sample_name <- NULL
  
  # Join tables so that the blank absorbance is applied as a column for all entries with the same blanking group
  plate_table_blanked <- dplyr::left_join(plate_table, summarized_blanks, by = c("Plate_number", "Blanking_group"))
  
  # Blank tables
  plate_table_blanked$Absorbance_blanked <- plate_table_blanked$Absorbance - plate_table_blanked$Blank_ave_abs
  
  # Remove unnecessary columns introduced during blanking
  plate_table_blanked$Blank_ave_abs <- NULL
  plate_table_blanked$Blank_stdDev_abs <- NULL
  
  return(plate_table_blanked)
  
}

# Description: checks std_summ to ensure everything looks okay. Can remove very low standards if below blank.
# Return: std_summ with possible removed standards (and throws a warning here)
check_standards <- function(std_summ, plate_table_blanked) {
  # Check if standards belong to more than one blanking group. Could imply that there are multiple types of standards in a single plate, which this script cannot handle.
  std_Blanking_group <- as.character(unique(std_summ$Blanking_group))
  
  # Check that only one Blanking Group is present and throw a warning otherwise -- handling multiple is not yet supported.
  if (length(std_Blanking_group) > 1) {
    warning(paste("Detected standards of multiple Blanking Groups in Plate ", 
                  unique(plate_table_blanked$Plate_number), ". the dataset. The script is not yet able to handle this. Should only be one type of standard per plate. Your data could be unusual...", sep = ""))
  }
  
  # Check if blank absorbance is greater than absorbance of lowest standard
  if (min(std_summ$Ave_abs_blanked) < 0) {
    # Identify number of standards below blank
    stds_below_blank <- dplyr::filter(std_summ, Ave_abs_blanked < 0)
    std_names_below_blank <- unique(stds_below_blank$Sample_name)
    std_names_below_blank_readable <- glue::collapse(std_names_below_blank, sep = ", ")
    
    # Throw a warning
    warning(paste("Plate_number ", unique(plate_table_blanked$Plate_number), ": blank has higher absorbance than ", nrow(stds_below_blank), 
                  " of the standards (",  std_names_below_blank_readable, "). Will throw out all standards below blank.", sep = ""))
    
    # Remove all standards with absorbance lower than blank
    std_summ <- dplyr::filter(std_summ, Ave_abs_blanked > 0)
  }
  
  return(std_summ)
}

# Description: determines standard curve for all plates in a provided input file
# Assume one standard for whole plate data file
# TODO - add support for multiple standard curves across the plates in the file. BUT this could be hard to implement - how to handle blanking groups with no associated standard?
make_standard_curve <- function(plate_table_blanked) {
  # plate_table <- plate_data_sep[[1]]
  
  ## Summarize standard curve data
  std_raw <- filter(plate_table_blanked, Sample_type == "Standard")
  # TODO - if proceeding with multi-standard support: change this to rely on core columns only but then allow for all other columns to impact grouping, in case the user wanted more than one group of standards
  std_grouped <- group_by(std_raw, Blanking_group, Sample_name, Standard_conc, Plate_number)
  std_summ <- summarise(std_grouped, Ave_abs_blanked = mean(Absorbance_blanked), StdDev_abs_blanked = sd(Absorbance_blanked))
  
  # Run check of standards and remove negative absorbance standards if needed
  std_summ <- check_standards(std_summ, plate_table_blanked)
  
  # Make linear trendline
  if (force_curve_through_zero == TRUE) {
    trendline <- lm(Ave_abs_blanked ~ 0 + Standard_conc, data = std_summ)
    # Forcing through origin: https://stackoverflow.com/a/18947967, accessed 170815
  } else {
    trendline <- lm(Ave_abs_blanked ~ Standard_conc, data = std_summ)
  }
  
  # Summarize key trendline values
  if (force_curve_through_zero == TRUE) {
    trendline_coeff <- c(0, coefficients(trendline)) # to make this match what the coefficients look like when not fixed to origin
  } else {
    trendline_coeff <- coefficients(trendline)
  }
  trendline_Rsquared <- summary(trendline)$r.squared
  trendline_summ <- data.frame("Intercept" = unname(trendline_coeff[1]), "Slope" = unname(trendline_coeff[2]), "R_squared" = trendline_Rsquared, "Plate_number" = unique(std_summ$Plate_number), stringsAsFactors = FALSE)
  
  # Return list of processed data
  std_curve_summary <- list(std_summ, trendline_summ)
  names(std_curve_summary) <- c("Summarized_standards", "Trendline")
  
  return(std_curve_summary)
}

# Description: summarizes unknowns by all metadata categories provided by user
summarize_unknowns <- function(plate_table_blanked) {
  
  ## Summarize standard curve data
  unk_raw <- filter(plate_table_blanked, Sample_type == "Unknown")
  # Group by all variables supplied by user, in case this helps to split samples apart for the desired factorial approach
  unk_grouped <- group_by_all(unk_raw)
  # unk_grouped <- group_by(unk_raw, Blanking_group, Treatment, Sample_name, Dilution_factor, Plate_number, Replicate)
  summarized_unknowns <- summarise(unk_grouped, Ave_abs_blanked = mean(Absorbance_blanked), StdDev_abs_blanked = sd(Absorbance_blanked))
  
  # Throw a warning if the blanking group does not exist for an unknown.
  if (anyNA(summarized_unknowns$Ave_abs_blanked) == TRUE) {
    # TODO - add code to determine the exact blanking group that is missing
    warning(paste("Plate ", unique(plate_table_blanked$Plate_number), ": at least one blanking group for unknowns has no corresponding blank. Data will contain NA values.", sep = ""))
  }
  
  return(summarized_unknowns)
}

# Description: checks concentration data and makes minor modifications specifically for plot aesthetics (e.g., no error bars below zero on log scale!)
# Return: summarized_unknowns_plotting_data (i.e., data table specifically for plotting)
check_concentrations <- function(summarized_unknowns) {
  # Throw a warning if some concentrations are negative
  if (min(summarized_unknowns$Ave_concentration) <= 0) {
    neg_values_positions <- which(summarized_unknowns$Ave_concentration <= 0)
    neg_values <- summarized_unknowns$Ave_concentration[neg_values_positions]
    num_neg_values <- length(neg_values)
    neg_values_readable <- glue::collapse(round(neg_values, 3), sep = ", ")
    
    # TODO - omit this entirely?    
    # # Omit those from standard curve plotting data frame (but keep in the unknowns data)
    # summarized_unknowns_plotting_data <- summarized_unknowns[-neg_values_positions,]
    
    # Report what was done
    if (num_neg_values == 1) {
      warning("Plate_number ", unique(summarized_unknowns$Plate_number), ": ", num_neg_values, " sample has a negative concentration based on standard curve (",
              glue::collapse(round(neg_values, 3), sep = ", "), ").", sep = "")
    } else if (num_neg_values > 1) {
      warning("Plate_number ", unique(summarized_unknowns$Plate_number), ": ", num_neg_values, " samples have negative concentrations based on standard curve (",
              neg_values_readable, ").", sep = "")
    }
    
    # (Probably rare:) Check if negative absorbances remain even after removing negative concentrations
    if (min(summarized_unknowns_plotting_data$Ave_abs_blanked) < 0) {
      neg_abs_positions <- which(summarized_unknowns_plotting_data$Ave_abs_blanked <= 0)
      
      warning(paste("Plate_number ", unique(summarized_unknowns$Plate_number), ": also note that ", num_neg_values, " additional samples have positive concentrations but negative blanked absorbances... something could be odd with the data.", sep = ""))
    }
    
  } else {
    # No issues with negative concentrations.
    # TODO - omit making this secondary data table if I end up choosing to never omit values from the plot.
    summarized_unknowns_plotting_data <- summarized_unknowns
  }
  
  # Generate error bar values in plotting data frame ahead of time and see if any are below zero (will cause error due to log scale)
  summarized_unknowns_plotting_data$errorbar_min <- summarized_unknowns_plotting_data$Ave_abs_blanked - summarized_unknowns_plotting_data$StdDev_abs_blanked
  summarized_unknowns_plotting_data$errorbar_max <- summarized_unknowns_plotting_data$Ave_abs_blanked + summarized_unknowns_plotting_data$StdDev_abs_blanked
  
  if (min(summarized_unknowns_plotting_data$errorbar_max) < 0) {
    # Max error bar should not be < 0 at this point, because negative data points for concentration were already removed
    warning(paste("Plate_number ", unique(summarized_unknowns$Plate_number), ": something seems wrong with the error bars on samples in the standard curve plots...", sep = ""))
    
  } else if (min(summarized_unknowns_plotting_data$errorbar_min) < 0) {
    # Eliminate negative values and replace with the value of the point itself (so bottom bars will essentially be unplotted)
    neg_errorbar_pos <- which(summarized_unknowns_plotting_data$errorbar_min < 0)
    summarized_unknowns_plotting_data$errorbar_min[neg_errorbar_pos] <- summarized_unknowns_plotting_data$Ave_abs_blanked[neg_errorbar_pos]
    
    warning(paste("Plate_number ", unique(summarized_unknowns$Plate_number), ": had to remove negative min. error bar positions for ", length(neg_errorbar_pos), 
                  " sample(s) in the std. curve plot in order to make the sample(s) plot-able. Unchanged in the actual data, however...", sep = ""))
  }
  
  return(summarized_unknowns_plotting_data)
}


# Description: creates standard curve plots for a single input file
# Return: list of two types of plots (with and without unknowns added)
plot_standard_curve <- function(summarized_standards, summarized_trendline, summarized_unknowns_plotting_data) {
  # Figure out where to put the trend line equation text on the plot
  min_x <- min(summarized_standards$Standard_conc)
  max_x <- max(summarized_standards$Standard_conc)
  min_y <- min(summarized_standards$Ave_abs_blanked)
  max_y <- max(summarized_standards$Ave_abs_blanked)
  # TODO - pull these out to the top of the script?
  x_coord <- (max_x - min_x) * 0.05 # arbitrary position 5% to the right of the y axis
  y_coord <- (max_y - min_y) * 0.8 # arbitrary position 80% above the x axis
  
  ## Make standards plot without samples
  std_plot <- ggplot(summarized_standards, aes(x = Standard_conc, y = Ave_abs_blanked)) +
    geom_smooth(method = "lm", se = T, colour = "purple") +
    geom_errorbar(aes(x = Standard_conc, ymin = Ave_abs_blanked-StdDev_abs_blanked, 
                      ymax = Ave_abs_blanked+StdDev_abs_blanked), width = 0, size = 0.8, alpha = 0.8) +
    geom_point(alpha = 0.9, size = 3) +
    annotate("text", x = x_coord, y = y_coord, 
             label = paste("y = ", round(summarized_trendline$Slope, digits = 5), 
                           "x + ", round(summarized_trendline$Intercept, digits = 5), 
                           "\n R^2 = ", round(summarized_trendline$R_squared, digits = 5), sep = ""), size = 3) +
    theme_bw() +
    # Add theme elements to make the plot look nice
    theme(panel.grid = element_blank(), title = element_text(size = 10), axis.title = element_text(size = 12), 
          strip.text = element_text(size = 10), strip.background = element_rect(fill = "#e6e6e6"),
          panel.border = element_rect(colour = "black", size = 1), panel.spacing.y = unit(3, "mm"), panel.spacing.x = unit(0, "mm"),
          axis.text.x = element_text(size = 10, colour = "black"), axis.text.y = element_text(size = 10, colour = "black"),
          axis.ticks = element_line(size = 0.5), axis.line = element_line(colour = "black", size = 0.5),
          legend.text = element_text(size = 7), legend.title = element_blank(),
          legend.key = element_rect(colour = "grey", size = 0.3), legend.key.size = unit(3, "mm"),
          legend.spacing = unit(1, "mm"), legend.box.just = "left", plot.margin = unit(c(2,2,2,2), "mm")) +
    #         See http://stackoverflow.com/questions/1330989/rotating-and-spacing-axis-labels-in-ggplot2 (approx. Jan 27, 2016) for vertical x-axis labels
    # scale_x_continuous(limits = c(0, NA)) +
    # scale_y_continuous(limits = c(0, NA)) +
    scale_x_log10() +
    scale_y_log10() +
    annotation_logticks() +
    xlab(paste("Concentration (", unique(summarized_unknowns_plotting_data$Concentration_units), ")", sep = "")) +
    ylab("Absorbance (blanked)") +
    ggtitle(paste("Plate_number: ", unique(summarized_unknowns_plotting_data$Plate_number), sep = ""))
  
  # Add on samples to the standard plot
  unk_plot <- std_plot +
    geom_errorbar(data = summarized_unknowns_plotting_data, 
                  aes(x = (Ave_concentration / Dilution_factor), 
                      ymin = errorbar_min, ymax = errorbar_max), 
                  width = 0, size = 0.8, alpha = 0.8, colour = "darkcyan") +
    geom_point(data = summarized_unknowns_plotting_data, 
               aes((Ave_concentration / Dilution_factor), Ave_abs_blanked), 
               shape = 21, alpha = 0.8, size = 3, fill = "darkcyan")
  
  output_plots <- list(std_plot, unk_plot)
  names(output_plots) <- c("std_curve_plot", "std_curve_plot_with_unknowns")
  
  return(output_plots)
  
}

# Description: converts sample absorbances to concentrations for a plate
# TODO - split into multiple functions (calculate, check, plot)
convert_to_concentration <- function(summarized_unknowns, std_curve_summary) {
  
  # Unpack the standard curve summary
  summarized_standards <- std_curve_summary$Summarized_standards
  summarized_trendline <- std_curve_summary$Trendline
  
  # Convert to concentration using standard curve (linear model) AND dilution factor
  summarized_unknowns$Ave_concentration <- (summarized_unknowns$Ave_abs_blanked - 
                                              summarized_trendline$Intercept) / summarized_trendline$Slope * summarized_unknowns$Dilution_factor
  
  # Get standard devations (also accounting for dilution factor)
  summarized_unknowns$StdDev_concentration <- (summarized_unknowns$StdDev_abs_blanked / 
                                                 summarized_trendline$Slope) * summarized_unknowns$Dilution_factor
  # For calculating std dev like this, see http://www.psychstat.missouristate.edu/introbook/sbk15.htm, accessed ~Jan. 2017
  
  # TODO - add a setting to toggle this for the user.
  summarized_unknowns$Concentration_units <- "uM"
  
  # Check concentration data and make minor modifications to improve plot readability (not affecting actual data) if needed
  summarized_unknowns_plotting_data <- check_concentrations(summarized_unknowns)
  
  # Make standard curve plots
  std_curve_plots <- plot_standard_curve(summarized_standards, summarized_trendline, summarized_unknowns_plotting_data)
  
  output_list <- list(summarized_unknowns, std_curve_plots$std_curve_plot, std_curve_plots$std_curve_plot_with_unknowns)
  names(output_list) <- c("calculated_concentrations", "std_plot", "std_plot_with_unknowns")
  # TODO - make list names consistent with above function
  return(output_list)
  
}

# Description: creates a 96 well plate-style figure of the parsed data for checking purposes
visual_check <- function(plate_table) {
  
  # Split wells into row and column
  plate_table$Well_row <- as.character(substr(plate_table$Well, start = 1, stop = 1))
  plate_table$Well_col <- as.numeric(substr(plate_table$Well, start = 2, stop = 3))
  
  # Make table of all wells in a 96 well plate to merge with main table
  # (in case some wells have been omitted by the user from the main table; this way, the entire 96 well plate will appear in the figure)
  wells_96 <- data.frame("Well_row" = c(rep("A", 12), rep("B", 12), rep("C", 12), rep("D", 12), rep("E", 12), rep("F", 12), rep("G", 12), rep("H", 12)),
                         "Well_col" = rep(c(1:12), 8), stringsAsFactors = FALSE)
  
  # Merge tables
  plate_table <- dplyr::full_join(plate_table, wells_96, by = c("Well_row", "Well_col"))
  
  # Put rows in order
  plate_table$Well_row <- factor(plate_table$Well_row, levels = rev(c("A", "B", "C", "D", "E", "F", "G", "H")), ordered = TRUE)
  
  # Make annotation text
  plate_table$Annotation <- paste(plate_table$Sample_name, " ", plate_table$Replicate, "\n", plate_table$Absorbance, sep = "")
  # Clean out ones with no sample
  for (i in 1:length(plate_table$Annotation)) {
    if (plate_table$Sample_name[i] == "" | is.na(plate_table$Sample_name[i]) == TRUE) {
      plate_table$Annotation[i] <- ""
    }
  }
  
  plate_diagram <- ggplot(plate_table, aes(factor(Well_col), Well_row)) +
    geom_point(aes(fill = Absorbance), shape = 21, size = 18) +
    geom_text(aes(label = Annotation), size = 2) +
    scale_fill_gradientn(colours = c("#ffffff", "#ff3399", "#660066"), limits = c(0,1)) + # Used limits to set absolute colour scale, as recommended at https://stackoverflow.com/a/21538521 (accessed Oct 2nd, 2017)
    xlab("") +
    ylab("") +
    ggtitle(unique(plate_table$Date))
  
  return(plate_diagram)
}

# Description: fully processes data for a single plate
calculate_plate_data <- function(plate_table) {
  summarized_blanks <- summarize_blanks(plate_table)
  
  plate_table_blanked <- blank_absorbances(plate_table, summarized_blanks)
  
  summarized_standards_list <- make_standard_curve(plate_table_blanked)
  
  summarized_unknowns <- summarize_unknowns(plate_table_blanked)
  
  # TODO - long-term, make separate functions for plotting versus summarizing unknowns
  calculated_concentrations_all <- convert_to_concentration(summarized_unknowns, summarized_standards_list)
  
  # Unpack output
  calculated_concentrations <- calculated_concentrations_all[[1]]
  std_plot <- calculated_concentrations_all[[2]]
  unk_plot <- calculated_concentrations_all[[3]]
  
  # Also unpack output from 'summarized_standards_list'
  summarized_standards <- summarized_standards_list[[1]]
  summarized_trendlines <- summarized_standards_list[[2]]
  
  # Run visual check
  plate_diagram <- visual_check(plate_table)
  
  output_list <- list(calculated_concentrations, summarized_blanks, summarized_standards, summarized_trendlines, std_plot, unk_plot, plate_diagram)
  names(output_list) <- c("Unknowns", "Blanks", "Standards", "Trendlines", "Std_curve_plot", "Std_curve_plot_with_unknowns", "Plate_diagrams")
  
  return(output_list)
  
}

# Description: Given a nested list with identical structure across level 1, moves the list item of identical 
# name or position from all lists into their own primary list
subset_list <- function(all_plate_data_calculated, item) {
  
  similar_items <- lapply(names(all_plate_data_calculated), 
                          function(x) { return(all_plate_data_calculated[[x]][[item]])})
  names(similar_items) <- names(all_plate_data_calculated)
  
  return(similar_items)
}

# Description: clarified information in the summary tables
summarize_processed_data <- function(plate_data_merged, separated_list_entries) {
  # Join tables from different plates
  # TODO - make this more elegant
  separated_list_entries[["Unknowns"]] <- dplyr::bind_rows(separated_list_entries[["Unknowns"]])
  separated_list_entries[["Blanks"]] <- dplyr::bind_rows(separated_list_entries[["Blanks"]])
  separated_list_entries[["Standards"]] <- dplyr::bind_rows(separated_list_entries[["Standards"]])
  separated_list_entries[["Trendlines"]] <- dplyr::bind_rows(separated_list_entries[["Trendlines"]])
  
  # Retrieve any additional metadata info provided by the user
  # Remove irrelevant information
  cols_to_remove <- c("Well", "Absorbance", "Sample_type", "Blanking_group", "Dilution_factor", "Standard_conc")
  cols_nums_to_remove <- match(cols_to_remove, colnames(plate_data_merged))
  extra_sample_info <- unique(plate_data_merged[,-(cols_nums_to_remove)])
  merging_cols <- c("Plate_number", "Sample_name", "Replicate", "Treatment") # to use with join later
  
  # Summarize the unknowns (samples) data and re-order for clarity
  separated_list_entries$Unknowns <- separated_list_entries$Unknowns[,c(5,3,6,2,4,1,7,8,9,10)]
  # Join in other sample info provided by the user
  separated_list_entries$Unknowns <- dplyr::inner_join(separated_list_entries$Unknowns, extra_sample_info, by = merging_cols)
  
  # Summarize standards and re-order for clarity
  separated_list_entries$Standards <- separated_list_entries$Standards[,c(5,3,4,2,1,6,7)]
  
  # Summarize blanks and re-order for clarity
  separated_list_entries$Blanks <- separated_list_entries$Blanks[,c(3,1,2,4,5)]
  
  # Summarize trendline and re-order for clarity
  separated_list_entries$Trendlines <- separated_list_entries$Trendlines[,c(4,2,1,3)]
  
  return(separated_list_entries)
  
}

# Description: writes Excel table of summarized data
write_excel_table <- function(output_filenames_prefix, summarized_table_list) {
  
  table_sheetnames <- names(summarized_table_list)
  
  # Save as Excel workbook with multiple sheets
  xlsx_table_filename <- paste(output_filenames_prefix, "_calculations.xlsx", sep = "")
  for (i in 1:length(summarized_table_list)) {
    if (i == 1) {
      write.xlsx2(as.data.frame(summarized_table_list[[i]]), xlsx_table_filename, 
                  sheetName = table_sheetnames[[i]], col.names=TRUE, row.names=FALSE, append=FALSE)
    } else {
      write.xlsx2(as.data.frame(summarized_table_list[[i]]), xlsx_table_filename, 
                  sheetName = table_sheetnames[[i]], col.names=TRUE, row.names=FALSE, append=TRUE)
    }
  }
  
}

# Description: prints a single PDF file with all plots in the input list (item_name within summarized_plot_list)
print_plot_file <- function(output_filenames_prefix, summarized_plot_list, item_name) {
  
  plot_filename <- paste(output_filenames_prefix, "_", item_name, ".pdf", sep = "")
  
  # TODO - make this more elegant
  if (item_name == "Plate_diagrams") {
    pdf(file = plot_filename, width = 10, height = 6)
  } else if (item_name != "Plate_diagrams") {
    pdf(file = plot_filename, width = 7, height = 7)
  }
  
  print(summarized_plot_list[[item_name]])
  # See https://stackoverflow.com/a/29834646, accessed 170815
  dev.off()
  
}

main <- function() {
  # Run command line version if requested
  if (RUN_COMMAND_LINE == TRUE) {
    parse_command_line_input()
  } else {
    # Like done in parse_command_line_input, determine if the inputs are pre-parsed or not
    if (is.null(opt$plate_data_filename) == FALSE | is.null(opt$sample_metadata_filename) == FALSE) {
      input_mode <- "raw"
    } else if (is.null(opt$pre_parsed_data_file) == FALSE) {
      input_mode <- "pre-parsed"
    } else if ((is.null(opt$plate_data_filename) == FALSE | is.null(opt$sample_metadata_filename) == FALSE) && is.null(opt$pre_parsed_data_file) == FALSE ) {
      stop("ERROR: Cannot have pre_parsed_data_file set at the same time as 'plate_data_filename' or 'sample_metadata_filename'. Exiting...")
    } else {
      stop("Something unexpected went wrong related to your input table variables. Exiting...")
    }
  }
  
  # Assign default naming prefix if not assigned by user
  if (is.na(output_filenames_prefix) == TRUE | is.null(output_filenames_prefix) == TRUE) {
    output_filenames_prefix <- substr(plate_data_filename[1], 1, nchar(plate_data_filename[1])-4)
  }
  
  # Startup messages
  cat(paste("Running 96_well_spec_analysis.R, version: ", SCRIPT_VERSION, "\n\n", sep = ""))
  if (input_mode == "raw") {
    cat(paste("Plate data filename:", plate_data_filename, "\n"))
    cat(paste("Metadata filename:", sample_metadata_filename, "\n"))
    cat(paste("Pre-parsed plate data filename:", "NOT APPLICABLE", "\n"))
  } else if (input_mode == "pre-parsed") {
    cat(paste("Plate data filenames:", "NOT APPLICABLE", "\n"))
    cat(paste("Metadata filename:", "NOT APPLICABLE", "\n"))
    cat(paste("Use pre-parsed plate data instead?:", pre_parsed_data_file, "\n"))
  }
  cat(paste("Prefix for output files:", output_filenames_prefix, "\n"))
  cat(paste("Force standard curves through zero?:", force_curve_through_zero, "\n"))
  cat("\n")
  
  ##### Import plate data
  # Take different courses of action depending on whether input_mode is 'raw' or 'pre-parsed'
  if (input_mode == "raw") {
    
    cat("Parsing plate data...\n")
    plate_data_merged <- parse_raw_data(plate_data_filename, sample_metadata_filename)
    cat("Successfully read in plate data and sample naming data.\n")
    
    # Export combined data
    merged_data_filename <- paste(output_filenames_prefix, "_raw_data.tsv", sep = "")
    write.table(plate_data_merged, file = merged_data_filename, sep = "\t", col.names = TRUE, row.names = FALSE)
    
  } else if (input_mode == "pre-parsed") {
    
    # Read in pre-merged plate/sample data
    plate_data_merged <- read.table(plate_data_filename, sep = "\t", header = TRUE, stringsAsFactors = FALSE)
    
    # Check if required columns exist. If they do not, exit early.
    required_colnames <- c("Plate_number", "Well", "Absorbance", "Sample_name", "Sample_type", "Blanking_group", "Dilution_factor", "Standard_conc")
    req_col_test <- unique(required_colnames %in% colnames(plate_data_merged))
    if (length(req_col_test) != 1 | req_col_test[1] == FALSE) {
      stop(paste("ERROR: Missing at least one required table column; see README.md. You need at least: '", glue::collapse(required_colnames, sep = ", ") ,"'. Exiting...", sep = ""))
    }
    
  }
  
  ##### Process standards and unknowns
  cat("Calculating concentrations...\n")
  
  # First, split the raw data into a list of individual plates
  plate_data_sep <- lapply(unique(plate_data_merged$Plate_number), 
                           function(x) {filter(plate_data_merged, Plate_number == x)})
  names(plate_data_sep) <- unique(plate_data_merged$Plate_number)
  
  # Calculate plate data
  all_plate_data_calculated <- lapply(names(plate_data_sep), 
                                      function(x) {calculate_plate_data(plate_data_sep[[x]])})
  names(all_plate_data_calculated) <- names(plate_data_sep)
  
  ##### Summarize output
  cat("Summarizing output...\n")
  
  # Move each list item into its own sub-list with like kinds
  separated_list_entries <- lapply(names(all_plate_data_calculated[[1]]), 
                                   function(x) { subset_list(all_plate_data_calculated, x) })
  # TODO - consider hard-coding this somewhere at the top. This line is also present in another function.
  names(separated_list_entries) <- c("Unknowns", "Blanks", "Standards", "Trendlines", "Std_curve_plot", "Std_curve_plot_with_unknowns", "Plate_diagrams")
  
  # Clean up output and separate tables from lists (manually!)
  summarized_data_list <- summarize_processed_data(plate_data_merged, separated_list_entries)
  summarized_table_list <- summarized_data_list[c(1:4)]
  summarized_plot_list <- summarized_data_list[c(5:7)]
  
  cat("Printing summary files...\n")
  # Write summary Excel table
  write_excel_table(output_filenames_prefix, summarized_table_list)
  
  # Also export unknowns as TSV
  table_filename_unknowns <- paste(output_filenames_prefix, "_unknowns.tsv", sep = "")
  write.table(summarized_data_list$Unknowns, file = table_filename_unknowns, sep = "\t", 
              col.names = TRUE, row.names = FALSE)
  
  # Print plots
  lapply(names(summarized_plot_list), function(x) { print_plot_file(output_filenames_prefix, 
                                                                    summarized_plot_list, x)})
  
  cat("\n96_well_spec_analysis.R: finished.\n\n")
  
}

main()
